- example/lib/main.dart
- lib/src/Widgets/Controlls/GhostButton/ghost_button.dart
- lib/src/Widgets/Controlls/GhostButton/ghost_button_scheme.dart
- lib/src/Widgets/Controlls/SecondaryButton/secondary_button.dart
- lib/src/Widgets/Controlls/SecondaryButton/secondary_button_scheme.dart
- lib/src/Widgets/Controlls/controll_parameter.dart
Задача:
https://github.com/admiral-team/admiralui-flutter/issues/27
> [27] - Secondary ghost button

- analysis_options.yaml
- example/windows/flutter/generated_plugins.cmake
- lib/src/Widgets/Views/Cell/base_cell.dart
- pubspec.yaml
> [28] - Added Linter

- example/lib/main.dart
- lib/admiralui_flutter.dart
- lib/theme/app_theme.dart
- lib/theme/app_theme_provider.dart
добавил темизацию + кнопку в demo по смене темы
> [20] - add theming to the demo

- example/lib/screens/big_informers_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/controls/link_control/link_control.dart
- lib/src/widgets/controls/tag_control/tag_control.dart
- lib/src/widgets/views/informers/big_informer.dart
- lib/src/widgets/views/informers/big_informer_scheme.dart
- lib/src/widgets/views/informers/small_informer.dart
> [137] - Very Big informer

- lib/admiralui_flutter.dart
- lib/src/widgets/controls/sliders/double_slider_widget.dart
- lib/src/widgets/controls/sliders/range_slider_thumb_shape.dart
> [142] - Double slider

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/cells/base_cell_screen.dart
- example/lib/screens/cells/trailing_cell_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/checkbox/checkbox_group.dart
- lib/src/widgets/checkbox/checkbox_title.dart
- lib/src/widgets/radio_button/radio_button.dart
- lib/src/widgets/radio_button/radio_group.dart
- lib/src/widgets/views/cell/trailing/date_percent_list_widget/date_percent_list_widget.dart
- lib/src/widgets/views/cell/trailing/date_percent_list_widget/date_percent_list_widget_scheme.dart
- lib/src/widgets/views/cell/trailing/image_subtitle_list_widget/image_subtitle_list_widget.dart
- lib/src/widgets/views/cell/trailing/image_subtitle_list_widget/image_subtitle_list_widget_scheme.dart
> [151] - Trailing cells

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/home_screen.dart
- example/lib/screens/toolbar_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/controls/input_number_control/input_number_control.dart
- lib/src/widgets/views/toolbar/toolbar_item.dart
- lib/src/widgets/views/toolbar/toolbar_widget.dart
- lib/src/widgets/views/toolbar/toolbar_widget_scheme.dart
> [166] -  Toolbar

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/home_screen.dart
- example/lib/screens/text_block/accordion_screen.dart
- example/lib/screens/text_block/text_block_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/views/text_block/drop_down/button_arrow_widget.dart
- lib/src/widgets/views/text_block/drop_down/button_arrow_widget_scheme.dart
- lib/src/widgets/views/text_block/drop_down/button_drop_down_widget.dart
- lib/src/widgets/views/text_block/drop_down/title_button_drop_down_widget.dart
- lib/src/widgets/views/text_block/drop_down/title_button_drop_down_widget_scheme.dart
> [700] - TextBlock Accordeon

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/text_block/link_text_block_screen.dart
- example/lib/screens/text_block/text_block_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/views/text_block/link/link_text_block_widget.dart
- lib/src/widgets/views/text_block/link/link_text_block_widget_scheme.dart
> [705] - Text Block Link

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/action_toast_screen.dart
- example/lib/screens/home_screen.dart
- example/lib/screens/notifications_screen.dart
- example/lib/screens/toast_informers_screen.dart
- example/lib/screens/toast_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/views/toast/action_toast_widget.dart
- lib/src/widgets/views/toast/action_toast_widget_scheme.dart
- lib/src/widgets/views/toast/animation/custom_animation.dart
- lib/src/widgets/views/toast/animation/custom_size_transition.dart
- lib/src/widgets/views/toast/animation/styled_toast.dart
- lib/src/widgets/views/toast/animation/styled_toast_enum.dart
- lib/src/widgets/views/toast/animation/styled_toast_manage.dart
- lib/src/widgets/views/toast/animation/styled_toast_theme.dart
- lib/src/widgets/views/toast/circle_timer_widget/circular_countdown_timer.dart
- lib/src/widgets/views/toast/circle_timer_widget/countdown_text_format.dart
- lib/src/widgets/views/toast/circle_timer_widget/custom_timer_painter.dart
- lib/src/widgets/views/toast/toast_parameter.dart
- lib/src/widgets/views/toast/toast_scheme.dart
- lib/src/widgets/views/toast/toast_style.dart
- lib/src/widgets/views/toast/toast_widget.dart
- pubspec.yaml
> [197] - Action toast

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/notifications_screen.dart
- example/lib/screens/toast_static.dart
- lib/src/widgets/views/toast/toast_scheme.dart
- lib/src/widgets/views/toast/toast_style.dart
> [195] - Static toast

- lib/src/widgets/views/textfields/textfield/textfield.dart
> [178] - Bottom Widget TextField

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/calendar/horizontal/calendar_vertical_screen.dart
- example/lib/screens/calendars_screen.dart
Добавить вертикальный календарь в демо
Добавлен календарь в демо
Calendar/Vertical
> [314] - Added Vertical Calendar to Demo

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/calendar/horizontal/calendar_horizontal_screen.dart
- example/lib/screens/calendar/horizontal/calendar_vertical_screen.dart
- example/lib/screens/calendars_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/views/calendar/components/calendar_controls/calendar_controls_view.dart
- lib/src/widgets/views/calendar/dates_data_source/calendar_dates_data_source.dart
- lib/src/widgets/views/calendar/dates_data_source/calendar_scroll_state.dart
- lib/src/widgets/views/calendar/dates_generator/calendar_dates_generator.dart
- lib/src/widgets/views/calendar/horizontal/calendar_horizontal_view.dart
- lib/src/widgets/views/calendar/vertical/calendar_vertical_page_view.dart
- lib/src/widgets/views/calendar/vertical/calendar_vertical_page_view_scheme.dart
- lib/src/widgets/views/calendar/vertical/calendar_vertical_view.dart
- lib/src/widgets/views/calendar/vertical/calendar_vertical_view_scheme.dart
Сделать вертикальный календарь 
вертикальный календарь 
Тестировать не надо, демо в другом реквесте
> [314] - Added vertical calendar

- example/lib/screens/currency_default_screen.dart
https://github.com/admiral-team/admiralui-flutter/issues/345
> [345] - Поправить отступы в Title в Currency

- example/lib/screens/standard_textfield_screen.dart
> [347] - Кнопка загораживается функционал в разделе TextFields 

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/buttons/buttons_rules_screen.dart
- example/lib/screens/buttons/buttons_screen.dart
**Описание задачи:**
Добавить кнопки в Раздел Rules
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102555-67653&mode=design&t=jztKbQWWwns2zI7V-0
Closes #343
> [343] - Add rules screen

- build/ios/fastlane/README.md
- build/ios/fastlane/report.xml
- example/ios/Runner/Info.plist
- pubspec.yaml
- version.json
> [BUMP] - 4

- example/lib/screens/tabs/outline_tabs_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/tabs/outline_tabs/outline_tab_item.dart
- lib/src/widgets/tabs/outline_tabs/outline_tabs.dart
**Описание задачи:**
Добавить функциональность в Outline Slider Tabs
Добавить в демо
**Ресурсы:**
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102619-69983&mode=design&t=Py7F1zi9O0BWdeeH-0
Closes #376
Сделать Outline Slider Tabs с Notification(c точками)
Сделать Outline Slider Tabs с Notification(c точками)
Outline Slider Tabs
> [376] - Сделать Outline Slider Tabs с Notification(c точками)

- example/lib/screens/tabs/icon_tabs_screen.dart
- lib/src/widgets/tabs/icon_tabs/icon_tab_item.dart
- lib/src/widgets/tabs/icon_tabs/icon_tab_item_scheme.dart
- lib/src/widgets/tabs/icon_tabs/icon_tabs.dart
- Проверить disabled state(наверно не работает) и добавить в дело
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102619-69983&mode=design&t=Py7F1zi9O0BWdeeH-0
**Фактический результат:**
**Ожидаемый результат:**
Closes #380
https://github.com/admiral-team/admiralui-flutter/assets/66259778/cfd06d67-d32c-4d85-a7f5-cbb7446dfb1a
> [380] - Fix icon tabs

- example/lib/screens/spinner_screen.dart
Не правильный расстояния между Tab и Spiner
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102619-64907&mode=design&t=Py7F1zi9O0BWdeeH-0
**Фактический результат:**
**Ожидаемый результат:**
Closes #382
Не правильный расстояния между Tab и Spiner
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102619-64907&mode=design&t=Py7F1zi9O0BWdeeH-0
**Фактический результат:**
**Ожидаемый результат:**
Closes #382
> [382] - Фикс отступа спиннера

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/pageControls/circle/page_control_circle_screen.dart
- example/lib/screens/pageControls/page_controls_screen.dart
- lib/src/widgets/controls/page_controls/circular_page_control/circular_page_control.dart
**Описание задачи:**
Реализовать экран PageControl -> Circle
**Ресурсы:**
[Ссылка на макеты или ресурсы...](https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?type=design&node-id=102619-64906&mode=design&t=Py7F1zi9O0BWdeeH-0)
Closes #373
https://github.com/admiral-team/admiralui-flutter/assets/66259778/0d389171-93e8-472c-815c-e427743fbd8e
> [373] - Fix circular page controll

- example/lib/screens/pageControls/circle/page_control_circle_screen.dart
> [TECH] - Fix PageControlCircleScreen

- build/ios/fastlane/report.xml
- version.json
> [BUMP] - 5

- example/lib/screens/feedback_screen.dart
- lib/src/widgets/controls/textfields/feedback/feedback_input_control.dart
Реализовать демо экран как в дизайне 
**Фактический результат:**
**Ожидаемый результат:**
Closes #417
> [417] - Fix feedback

- example/lib/screens/chat/input/chat_input_screen.dart
- example/lib/screens/chat/text_operation/text_operation_screen.dart
- example/lib/screens/chat/uploading_photo/uploading_photo_screen.dart
- lib/admiralui_flutter.dart
- lib/src/widgets/chat/chat_input/chat_input.dart
- lib/src/widgets/chat/chat_input/chat_input_file_button.dart
- lib/src/widgets/chat/chat_input/chat_input_file_button_scheme.dart
- lib/src/widgets/chat/chat_input/chat_input_scheme.dart
- lib/src/widgets/chat/uploading_photo/cell/uploading_photo_cell_item.dart
- lib/src/widgets/chat/uploading_photo/cell/uploading_photo_grid_corner_style.dart
- lib/src/widgets/chat/uploading_photo/cell/uploading_photo_item.dart
- lib/src/widgets/chat/uploading_photo/cell/uploading_photo_view.dart
- lib/src/widgets/chat/uploading_photo/cell/uploading_photo_view_scheme.dart
- lib/src/widgets/chat/uploading_photo/grid/uploading_photo_grid.dart
- lib/src/widgets/chat/uploading_photo/grid/uploading_photo_grid_builder.dart
- lib/src/widgets/controls/page_controls/circular_page_control/circular_painter.dart
- Нет заголовка Default
- Поставь даты как в демо
- Нет галочки в статусе сообщения
**Фактический результат:**
**Ожидаемый результат:**
Closes #412
411, 412, 413
411, 412, 413
Чат
> [411, 412, 413] - Баги чата

- .github/workflows/dart.yml
- remote_demo/ios/Runner.xcodeproj/project.pbxproj
- remote_demo/ios/Runner/Info.plist
**Описание задачи:**
Краткое описание задачи...
**Фреймворк**
Фреймворк для которого нужно выполнить доработку (Flutter)...
**Ресурсы:**
Ссылка на макеты или ресурсы...
Closes #452
Добавить provision profile для remote_demo iOS
Добавить provision profile для remote_demo iOS
> [452] - Добавить provision profile для remote_demo iOS

- example/lib/screens/badges/normal_badges_screen.dart
- example/lib/screens/badges/small_badges_sreen.dart
- example/lib/screens/big_informers_screen.dart
- example/lib/screens/informers/notifications_screen.dart
- example/lib/screens/informers/toast_informers_screen.dart
- example/lib/screens/informers_screen.dart
- example/lib/screens/number_screen.dart
- example/lib/screens/tabs/tabs_screen.dart
- example/lib/screens/tabs/underlineTabs/underline_tabs_screen.dart
- example/lib/screens/textfields_screen.dart
Фактический результат
ОР
Closes #442
> [442] - Fix titles for all bugs screen

- lib/admiralui_flutter.dart
- lib/src/widgets/controls/sliders/double_slider_widget.dart
- lib/src/widgets/controls/sliders/slider_line_painter.dart
- lib/src/widgets/controls/sliders/slider_widget.dart
Полоска слайдера не от края
Closes #415
https://github.com/admiral-team/admiralui-flutter/assets/100690555/ac757e79-024b-4637-b53b-c9e1cde63f53
)
> [415] - Slider Line Width

- build/ios/fastlane/Fastfile
- build/ios/fastlane/release.rb
Исправить ошибки в set version
Fix set version
> [TECH] - Fix set version

- build/ios/fastlane/report.xml
- version.json
> [BUMP] - 13

- .github/workflows/dart.yml
- example/lib/main.dart
> [TECH] - Фикс локального билда ios

- example/lib/screens/textfields_screen.dart
Поправить цвет нав бара в темной теме
Closes #476
> [476] - Fix text field appbar color

- build/ios/fastlane/README.md
- build/ios/fastlane/report.xml
- example/ios/Runner/Info.plist
- version.json
> [BUMP] - 14

- example/lib/screens/pageControls/page_controls_screen.dart
Поправить Нав бар в темной теме на PageControl 
Closes #509
> [509] - BackgroundColor fix

- .github/workflows/dart.yml
- example/android/app/build.gradle
- example/android/build.gradle
- example/android/buildSrc/src/main/groovy/AdmiralReleaseNotesTask.groovy
- example/android/google-services.json
- example/android/release-notes.txt
- example/android/tester-groups.txt
> [TECH] - handle android firebase app distribution

- example/lib/screens/textfields/pin_code_screen.dart
- lib/src/widgets/controls/textfields/pincode/pincode_item_view.dart
- lib/src/widgets/controls/textfields/pincode/pincode_view.dart
Сделать так же как в демо на iOS PinCode
https://github.com/admiral-team/admiralui-flutter/assets/8963238/ee40e361-02e3-44a2-88a1-efbc5dcdfad5
Closes #540
https://github.com/admiral-team/admiralui-flutter/assets/66259778/eb69f3d5-8940-4ee4-9fab-da0c4138a23a
> [540] - Fix pin code

- build/ios/fastlane/report.xml
- version.json
> [BUMP] - 17

- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/Info.plist
> [TECH] - Update bundle

- build/ios/fastlane/report.xml
- example/ios/Runner/Info.plist
- version.json
> [BUMP] - 18

- build/ios/fastlane/report.xml
- version.json
> [BUMP] - 19

- build/ios/fastlane/report.xml
- example/ios/Runner/Info.plist
- version.json
> [BUMP] - 20

- example/lib/screens/textfields/number_screen.dart
- example/lib/screens/themes/theme_colors_screen.dart
- example/lib/screens/themes/theme_fonts_screen.dart
- example/lib/screens/themes/themes_screen.dart
Проблема в нав баре Themes в темной теме
Closes #598
https://github.com/admiral-team/admiralui-flutter/issues/598
https://github.com/admiral-team/admiralui-flutter/issues/599
https://github.com/admiral-team/admiralui-flutter/issues/600
https://github.com/admiral-team/admiralui-flutter/issues/601
> [598] - Fix navbar color dark theme

- lib/src/admiral_icons.json
> [TECH] - Add icons json

- build/ios/fastlane/report.xml
- example/assets/version.json
- example/ios/Runner/Info.plist
> [BUMP] - 22

- .github/workflows/dart.yml
- example/assets/templates/primary_buttons_template.json
- example/assets/templates/templates.json
- example/lib/domain/use_cases/template/impl/template_impl.dart
- example/lib/main.dart
- example/lib/navigation/tab_navigation_ai.dart
- example/lib/screens/ai/ai_screen.dart
- example/lib/screens/ai/block/chat_template/chat_template_screen_cubit.dart
- example/lib/screens/ai/block/template/template_screen_cubit.dart
- example/lib/screens/ai/chat_template_screen.dart
- example/lib/screens/ai/template_screen.dart
- example/lib/screens/ai/templates_screen.dart
- example/lib/screens/ai/view_models/primary_button_view_model.dart
- example/lib/screens/root_screen.dart
- example/test/golden_test.dart
https://github.com/user-attachments/assets/fcd81e2d-9302-45a9-b87b-5134bdc482e2
> [TECH] - AI primary buttons

- build/ios/fastlane/report.xml
- example/assets/version.json
- example/ios/Runner/Info.plist
- pubspec.yaml
> [RC] - 1.5.7 Dev

- example/assets/templates/ghost_buttons_template.json
- example/assets/templates/secondary_buttons_template.json
- example/assets/templates/templates.json
- example/lib/domain/use_cases/template/impl/template_impl.dart
- example/lib/screens/ai/template_screen.dart
- example/lib/screens/ai/view_models/ghost_button_view_model.dart
- example/lib/screens/ai/view_models/secondary_button_view_model.dart
Обнаружил нестандартное поведение ghost buttons на экране скролл вью. Не верная ширина. Нужно завести задачу на фикс
> [TECH] - Secondary ghost buttons templates

- build/ios/fastlane/report.xml
- example/assets/version.json
> [BUMP] - 23

- example/assets/templates/buttons_rules_template.json
- example/assets/templates/templates.json
- example/lib/domain/use_cases/template/impl/template_impl.dart
- example/lib/screens/ai/template_screen.dart
- example/lib/screens/ai/view_models/check_box_view_model.dart
- example/lib/screens/ai/view_models/expanded_view_model.dart
- example/lib/screens/ai/view_models/link_control_view_model.dart
- example/lib/screens/ai/view_models/text_view_model.dart
https://github.com/user-attachments/assets/29bf4ae9-a2c2-4e58-b3bb-bee69ec925b1
> [TECH] - AI rules template

- example/assets/templates/primary_buttons_template.json
- example/lib/screens/ai/template_screen.dart
> [TECH] - Fix buttons

- build/ios/fastlane/report.xml
- example/assets/version.json
> [BUMP] - 24

- example/lib/navigation/tab_navigator_home.dart
> [TECH] - Fix imports files

- example/lib/screens/themes/theme_colors_screen.dart
> [TECH] - Fix import files

- example/lib/navigation/tab_navigator_home.dart
- example/lib/screens/icons/icon_tab_state.dart
- example/lib/screens/icons/icons_screen.dart
- example/lib/screens/icons_screen.dart
Closes #763
https://github.com/user-attachments/assets/3ea572d6-3645-434a-a462-2c9e38d5dcdc
> [763] - Add filter icons

- example/pubspec.yaml
> [TECH] - Fix pubspec for web icons
